services:
  server:
    image: hegyhati/hackathon_2024_autumn_engine
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - 8000:5000
    volumes:
      - ./test_maps:/app/test_maps
      - ./conf.py:/app/conf.py

  viewer:
    image: hegyhati/hackathon_2024_autumn_viewer
    ports:
     - 80:80
    environment:
      - VITE_BACKEND_URL=localhost:8000
    depends_on:
      - server
